import { describe, it, expect } from 'vitest';
import { diffJson } from './jsonDiff';

describe('diffJson', () => {
  it('identical objects (empty result)', () => {
    const obj = { a: 1, b: { c: true }, d: [1, 2] };
    expect(diffJson(obj, obj)).toEqual([]);
    
    const clone = { a: 1, b: { c: true }, d: [1, 2] };
    expect(diffJson(obj, clone)).toEqual([]);
  });

  it('added key', () => {
    const prev = { a: 1 };
    const next = { a: 1, b: 2 };
    expect(diffJson(prev, next)).toEqual([
      { path: 'b', kind: 'added', newValue: 2 }
    ]);
  });

  it('removed key', () => {
    const prev = { a: 1, b: 2 };
    const next = { a: 1 };
    expect(diffJson(prev, next)).toEqual([
      { path: 'b', kind: 'removed', oldValue: 2 }
    ]);
  });

  it('changed primitive', () => {
    const prev = { a: 1 };
    const next = { a: 2 };
    expect(diffJson(prev, next)).toEqual([
      { path: 'a', kind: 'changed', oldValue: 1, newValue: 2 }
    ]);
  });

  it('nested object change', () => {
    const prev = { a: { b: { c: 1 } } };
    const next = { a: { b: { c: 2, d: 3 } } };
    expect(diffJson(prev, next)).toEqual([
      { path: 'a.b.c', kind: 'changed', oldValue: 1, newValue: 2 },
      { path: 'a.b.d', kind: 'added', newValue: 3 }
    ]);
  });

  it('array element added/removed/changed', () => {
    const prev = { arr: [1, 2, 3] };
    const next = { arr: [1, 4] };
    expect(diffJson(prev, next)).toEqual([
      { path: 'arr[1]', kind: 'changed', oldValue: 2, newValue: 4 },
      { path: 'arr[2]', kind: 'removed', oldValue: 3 }
    ]);
  });

  it('type change at same path', () => {
    const prev = { a: 1 };
    const next = { a: [1] };
    expect(diffJson(prev, next)).toEqual([
      { path: 'a', kind: 'changed', oldValue: 1, newValue: [1] }
    ]);
    
    const prev2 = { a: { b: 1 } };
    const next2 = { a: null };
    expect(diffJson(prev2, next2)).toEqual([
      { path: 'a', kind: 'changed', oldValue: { b: 1 }, newValue: null }
    ]);
  });

  it('diffs real captured data correctly', () => {
    // Read the actual fixtures generated by the check-normal.ts script
    // vitest runs in a node environment, so we can use dynamic imports or fs
    const fs = require('fs');
    const path = require('path');
    
    const fixturesDir = path.join(process.cwd(), 'src/lib/test/fixtures');
    const prevFile = path.join(fixturesDir, 'ctx_ctx_report_1.json');
    const nextFile = path.join(fixturesDir, 'ctx_ctx_report_21.json');
    
    expect(fs.existsSync(prevFile)).toBe(true);
    expect(fs.existsSync(nextFile)).toBe(true);

    const prev = JSON.parse(fs.readFileSync(prevFile, 'utf-8'));
    const next = JSON.parse(fs.readFileSync(nextFile, 'utf-8'));

    const diffs = diffJson(prev, next);
    
    expect(diffs.length).toBeGreaterThan(0);

    // Helper to get nested value by string path (like "a.b[1].c")
    const getValueByPath = (obj: any, pathStr: string) => {
      let current = obj;
      const parts = pathStr.replace(/\[(\w+)\]/g, '.$1').split('.');
      for (const part of parts) {
        if (current == null) return undefined;
        current = current[part];
      }
      return current;
    };

    for (const d of diffs) {
      if (d.kind === 'added' || d.kind === 'changed') {
        const nextVal = getValueByPath(next, d.path);
        expect(nextVal).not.toBeUndefined();
        expect(nextVal).toEqual(d.newValue);
      }
      if (d.kind === 'removed' || d.kind === 'changed') {
        const prevVal = getValueByPath(prev, d.path);
        expect(prevVal).not.toBeUndefined();
        expect(prevVal).toEqual(d.oldValue);
      }
    }
  });

  it('diffs 500KB objects in under 100ms', () => {
    const fs = require('fs');
    const path = require('path');
    const largeFixturePath = path.join(process.cwd(), 'src/lib/test/fixtures/ctx_large_500kb.json');
    expect(fs.existsSync(largeFixturePath)).toBe(true);
    
    const largeFixture = JSON.parse(fs.readFileSync(largeFixturePath, 'utf-8'));
    const modifiedRaw = { ...largeFixture, sections: [...largeFixture.sections] };
    modifiedRaw.sections[0] = { ...modifiedRaw.sections[0], title: 'CHANGED' };
    
    // Simulate incoming websocket payload (no shared references)
    const modified = JSON.parse(JSON.stringify(modifiedRaw));
    
    const start = performance.now();
    const diff = diffJson(largeFixture, modified);
    const elapsed = performance.now() - start;
    
    console.log('diff time:', elapsed, 'ms');
    expect(diff).toHaveLength(1);
    expect(diff[0]).toEqual({
      path: 'sections[0].title',
      kind: 'changed',
      oldValue: largeFixture.sections[0].title,
      newValue: 'CHANGED',
    });
  });
});
